
const MOCKING_DATA = {
  "mocking_lines": [
    "Ha! Swing and a miss, try harder!",
    "Wrong! Even I saw that coming!",
    "Epic flop! Back to basics!",
    "Nope! Total brain hiccup!",
    "Bzzzt! Zap, you're out!",
    "Fail! Chuckles all around!",
    "Oof! That stung a bit!",
    "Wrongo! Hilarious slip-up!",
    "Ha ha! Crash and burn!",
    "Missed! So close, yet nah!",
    "Pathetic! Giggles incoming!",
    "Incorrect! Laugh track plays!",
    "LOL! Adorably off-base!",
    "Wrong! You're killing me!",
    "Busted! Epic whoopsie!",
    "Fail whale! Dive deep!",
    "Ha! Your shot fizzled!",
    "Nope! Comedy gold mine!",
    "Wrong answer! Chef's kiss fail!",
    "Giggle snort! So bad!",
    "Ouch! That bombed hard!",
    "Fail! Emojis rolling eyes!",
    "Ha ha! Twister gone wrong!",
    "Wrong! Vacation mode on!",
    "Bzzzt! Glitch alert!",
    "Miss! Vault empty now!",
    "Pathetic! Kick it up!",
    "LOL fail! Zero learning!",
    "Incorrect! Tutoring time yet?",
    "Ha! DOA attempt!",
    "Nope! Ran away fast!",
    "Wrong! No substance here!",
    "Epic derp! Zero hero!",
    "Fail! Ghosted you bad!",
    "Giggle fest! Many levels!",
    "Oof! Collapsed flat!",
    "Ha ha! Protection needed!",
    "Busted! Tantrum level!",
    "Wrong! Diet required!",
    "Missed! Aim words better!",
    "Pathetic! Guffaw time!",
    "LOL! Bad pun alert!",
    "Incorrect! Approve that mess!",
    "Ha! Diet gone wrong!",
    "Nope! Catastrophe hit!",
    "Fail! Exiled forever!",
    "Wrongo! Caveman style?",
    "Epic blunder! Shame hall!",
    "Giggle zap! Confirmed glitch!",
    "Ouch! Cease and desist!",
    "Ha ha! Believable mistake!",
    "Bzzzt! Avalanche incoming!",
    "Miss! Page gone missing!",
    "Pathetic! Twist you're wrong!",
    "LOL! Flu hit hard!",
    "Incorrect! Spectacular mess!",
    "Ha! Fragmented fail fab!",
    "Nope! Void sucks in!",
    "Wrong! Jackpot hit!",
    "Fail fiesta! Party on!",
    "Epic error! Flop worthy!",
    "Giggle storm! Ahead wrong!",
    "Oof! Nonsense verboten!",
    "Ha ha! Rejected flat!",
    "Busted! Embargo now!",
    "Miss! Dirt level aim!",
    "Pathetic! Shadow wins big!",
    "LOL loss! Days chuckles!",
    "Incorrect! Therapy needed!",
    "Ha! Bounced check!",
    "Nope! Lame conjugate!",
    "Wrong! Scene fleeing!",
    "Fail frenzy! Moonwalk time!",
    "Epic whoops! Noob hall!",
    "Giggle grenade! Ego boom!",
    "Ouchie! Gangrene got!",
    "Ha ha! Drained dry!",
    "Bzzzt! Short circuit!",
    "Miss! Blunder bullseye!",
    "Pathetic! Float lead!",
    "LOL! Failing legend!",
    "Incorrect! Disowned now!",
    "Ha! Cold served!",
    "Nope! Abdicated throne!",
    "Wrong! Herro fail!",
    "Fail fireworks! Stupid spectacular!",
    "Epic! Encore embarrassment?",
    "Giggle! End times!",
    "Oof! Imminent failure!",
    "Ha ha! Surrender negotiate!",
    "Busted! Felony fluency!",
    "Wrong! Parade of fails!",
    "Nope! Gaffe galore!",
    "Fail! Snicker session!",
    "Ha! Flop total!",
    "Missed! Error rookie!",
    "Incorrect! Laughable lot!",
    "Wrong! Whoops epic!",
    "Fail! Slip syntax!"
  ]
};

export default MOCKING_DATA;
